version: "3"

services:
  # server:
  # container_name: server
  # build: ./server
  # ports:
  #    - "8080:8080"
  #    - "5000:5000"

  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - "./config/blackbox-exporter.yml:/config/blackbox-exporter.yml"
    command: --config.file=/config/blackbox-exporter.yml

