version: "3.7"
services:
  tomcat:
    container_name: tomcat
    image: tomcat:latest
    volumes:
      - /home/daou_docker/exporters/jmx-exporter/tomcat/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - /home/daou_docker/exporters/jmx-exporter/tomcat/etc/config.yaml:/usr/local/tomcat/etc/config.yaml
       - /home/daou_docker/exporters/jmx-exporter/jmx_prometheus_javaagent-0.16.1.jar:/usr/local/tomcat/etc/jmx_prometheus_javaagent-0.16.1.jar
    ports:
      - "8080:8080"

