version: "3"

services:
  
  httpd:
    container_name: httpd
    image: httpd:latest
    ports:
      - 8080:80
    volumes:
      - ./httpd/conf/httpd.conf:/home/daou_docker/exporters/apache/httpd/conf/http.conf
      - ./httpd/conf.d/server-status.conf:/home/daou_docker/exporters/apache/httpd/conf.d/server-status.conf
  
  apache-exporter:
    container_name: apache-exporter
    image: motork/apache_exporter:latest
    ports:
      - 9117:9117
    command: '--scrape_uri="http://httpd/server-status?auto"'

